### ISSUE TITLE
是否显示版本号？是的话，又如何显示？

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/packages#12]
https://github.com/emacs-china/packages/pull/2#issuecomment-265105856:

| Package  |  Description                    |  GNU                                                    | melpa-stable                                                     | melpa                                                         |
|----------|---------------------------------|---------------------------------------------------------|-------------------------------------------------------------------|---------------------------------------------------------------|
| dash     | A modern list library for Emacs | [2.12.0](https://elpa.gnu.org/packages/dash-2.12.0.tar) | [2.13.0](http://melpa-stable.milkbox.net/packages/dash-2.13.0.el) | [20161121.55](https://melpa.org/packages/dash-20161121.55.el) |

但是有 7 个 ELPA，都分别占一列的话，可能宽度不够。

https://github.com/emacs-china/packages/pull/2#issuecomment-265115997:

```
| Package   | Version             | Description                                          |
|-----------+---------------------+------------------------------------------------------|
| dash      | gelpa-2.12.0        | A modern list library for Emacs                      |
|           | melpa-stable-2.13.0 |                                                      |
|           | melpa-20161121.55   |                                                      |
|-----------+---------------------+------------------------------------------------------|
| helm      | melpa-20161202.820  | Helm is an Emacs incremental and narrowing framework |
|           | melpa-stable-2.3.3  |                                                      |
|-----------+---------------------+------------------------------------------------------|
| 2048-game | melpa-20151026.1233 | play 2048 in Emacs                                   |
|-----------+---------------------+------------------------------------------------------|
| seq       | gelpa-2.19          | Sequence manipulation functions                      |
|-----------+---------------------+------------------------------------------------------|
| gtk-look  | user42-29           | lookup Gtk and Gnome documentation.                  |
```

---
Pending #11

**Comment by twlz0ne** [comment]
就第二种方式吧，有的不一定有三个版本，列空着也不好看

**Comment by xuchunyang** [comment]
ELPA 数量比较多，一个成一列的话，宽度很可能不够：

```
| Package           | Description   | GNU | melpa-stable | melpa | Marmalade | Org | sunrise-commander | user42 |
|-------------------+---------------+-----+--------------+-------+-----------+-----+-------------------+--------|
| dash              | list lib      | x   | x            | x     | x         |     |                   |        |
| org               | hmm, org      | x   |              |       |           | x   |                   |        |
| gtk-look          | devehlp alter |     |              |       |           |     |                   | x      |
| sunrise-commander | don't know    |     |              |       |           |     | x                 |        |
```

> 就第二种方式吧，

第二种不知道视觉效果会怎样，我有些担心会比较难看。

我也考虑过不显示版本信息，给每个 Package 单独做一个介绍页面 #3 ，然后在那里写版本信息。

**Comment by tumashu** [comment]
可以用弹出提示的方式显示

**Comment by twlz0ne** [comment]
![emacs-china-package-versions](https://cloud.githubusercontent.com/assets/2653486/21360199/dfdc24ce-c719-11e6-879a-c6442fa28333.png)

**Comment by xuchunyang** [comment]
还是有些麻烦，并且现在 Package 自己的页面中也包括了这个信息，暂时决定不显示。
