### ISSUE TITLE
给每一个 Package 做一个单独的介绍页面

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/packages#3]
类似与：

- https://elpa.gnu.org/packages/dash.html
- https://melpa.org/#/dash

应该至少包括以下信息：

- Name
- Description
- Commentary
- Homepage if any
- 所在的上游 ELPA，以及相应的版本号
- 指向 Emacs China ELPA 镜像的下载链接

**Comment by geekplux** [comment]
现在每个 package 点击进去不是就能看见这些详细信息吗？所以我们是要做个自己的？

**Comment by xuchunyang** [comment]
> 现在每个 package 点击进去不是就能看见这些详细信息吗？

如果 Package 有指定项目主页的话，现在链接到的是 Package 的项目主页。如果没有的话（比如 `dash`），链接到的是 `https://elpa.emacs-china.org/packages/`。

> 我们是要做个自己的？

是，类似于 <kbd>C-h P</kbd> （`describe-package`）产生的结果，GNU ELPA 和 MELPA 上也有。

**Comment by xuchunyang** [comment]
Done，一个例子：https://elpa.emacs-china.org/packages/dash/
