### ISSUE TITLE
改进分页按钮

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/packages#9]
>  分页按钮很不协调
> https://github.com/emacs-china/packages/pull/2#issuecomment-265063701

- [ ] 改成有按钮的效果，现在只是文本链接
- [ ] 只有一页时不显示分页按钮？

**Comment by twlz0ne** [comment]
![emacs_packages pagination-button](https://cloud.githubusercontent.com/assets/2653486/21097530/e22d5868-c09f-11e6-911b-46398a251783.gif)

分页按钮布局和样式可以讨论一下，我这里简单“画”了一组：

- 按钮边框厚度 `1px` ? `2px`?;
- 按钮边框颜色 `#e0e0e0`，跟搜索框一致；
- 当前页背景略浅 `#ececec`，隐约能看见边框; 悬停（Hover）也使用这个颜色
- ...

**Comment by xuchunyang** [comment]
我不懂前端，只能主观上感受下，给不出具体的看法来。

MELPA （ https://melpa.org/#/ ）上的分页按钮的布局看起来不错（不求全面，简单），或许可以有所借鉴。

**Comment by twlz0ne** [comment]
https://melpa.org/#/  用的是 http://getbootstrap.com/ 这个前端库

**Comment by twlz0ne** [comment]
我把之前写好的分页代码稍微修改了一下 pr https://github.com/emacs-china/packages/pull/17

没有使用 bootstrap, 手写了几个样式，尽量接近当前页面风格：

![elpa_packages](https://cloud.githubusercontent.com/assets/2653486/25473991/291b7d02-2b64-11e7-980c-71ffd31031fa.gif)
